"""added orders  table

Revision ID: 095e9eb2f88d
Revises: 19d3077c3414
Create Date: 2023-09-05 10:08:18.683537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095e9eb2f88d'
down_revision = '19d3077c3414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
