"""Add review column to Produce table

Revision ID: 2605d41ad264
Revises: adda4dbfe938
Create Date: 2023-09-06 13:34:41.078278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2605d41ad264'
down_revision = 'adda4dbfe938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('orders', 'produce_name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    op.add_column('produce', sa.Column('review', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produce', 'review')
    # op.alter_column('orders', 'produce_name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # ### end Alembic commands ###
