"""updated  orders  table to have a column produce name

Revision ID: adda4dbfe938
Revises: d9456e92799d
Create Date: 2023-09-05 21:56:50.843498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adda4dbfe938'
down_revision = 'd9456e92799d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('produce_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'produce_name')
    # ### end Alembic commands ###
